apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shawnpearson-service-dependency
  description: |
    Shawn Pearson second service.
  links:
    - title: Website
      url: http://harness.io
  annotations:
    github.com/project-slug: harnessworkshop/idp-workshop
    backstage.io/techdocs-ref: dir:../
    lighthouse.com/website-url: https://harness.io
  #    harness.io/services: |
  #      paymentService: https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/cd/orgs/demoorg/projects/paymentservice/services/paymentservice
  #    harness.io/pipelines: |
  #      paymentService: https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/cd/orgs/demoorg/projects/paymentservice/pipelines/harnesscicd/pipeline-studio?storeType=INLINE
  #  labels:
  #    key1: value1
  tags:
    - shawnpearson
spec:
  type: service
  owner: TeamB
  lifecycle: experimental
  system: Demo
  dependsOn:
    - component:default/shawnpearson-service
#  consumesApis:
#    - user-api
#  providesApis:
#    - example-api
